const model = require('./collectingPoint.model');

const collectingPoints = [
  {
    establishment: 'kedge',
    article: model.BULK,
    label: '1 tote-bag de textile',
    reward: 'Récompenses by Backmarket, Pumpkin...',
    rewards: {
      title: 'Oups pardon ! TES récompenses',
      items: [
        { company: 'BackMarket', reward: "15€ sur 200€ d'achat" },
        { company: 'Pumpkin', reward: '10€ crédité sur ton compte' },
        { company: 'Rinku', reward: '-40% sur le bureau Tokyo' },
      ],
      note: 'Une fois ton dépôt effectué, tu recevras tes récompenses par mail.',
    },
    successLabel: 'Ton tote-bag de textile',
    successWhere: 'sur le CAMPUS HALL B',
    successWhen: 'Du 18 au 22 janvier',
    startDate: '2020-10-16',
    endDate: '2021-01-22',
  },
  {
    establishment: 'kedge',
    image: 'kedge-smartphone.jpg',
    article: model.SMARTPHONE,
    label: '1 smartphone',
    reward: 'Récompenses by Backmarket, Pumpkin...',
    rewards: {
      title: 'Oups pardon ! TES récompenses',
      items: [
        { company: 'BackMarket', reward: "15€ sur 200€ d'achat" },
        { company: 'Pumpkin', reward: '10€ crédité sur ton compte' },
        { company: 'Rinku', reward: '-40% sur le bureau Tokyo ' },
      ],
      note: 'Une fois ton dépôt effectué, tu recevras tes récompenses par mail.',
    },
    successLabel: 'Ton smartphone',
    successWhere: 'sur le CAMPUS HALL B',
    successWhen: 'Du 18 au 22 janvier',
    startDate: '2020-10-16',
    endDate: '2021-01-22',
  },
  {
    establishment: 'cabesto',
    article: model.WETSUIT,
    label: '1 combinaison néoprène',
    reward: "10€ pour 80€ d'achat",
    successLabel: 'Ta combinaison néoprène',
  },
  {
    establishment: 'lilly_p',
    article: model.BULK,
    successLabel: 'Ton tote-bag de textile',
    label: '1 tote-bag de textile',
    reward: '10% sur toute la boutique',
  },
  {
    establishment: 'lilly_p',
    article: model.JEAN,
    successLabel: 'Tes 2 jeans',
    label: '2 jeans',
    reward: '10% sur toute la boutique',
  },
  {
    establishment: 'atao',
    article: model.BULK,
    successLabel: 'Ton tote-bag de textile',
    label: '1 tote-bag de textile en vrac',
    reward: '10% sur toute la boutique',
  },
  {
    establishment: 'atao',
    article: model.JEAN,
    successLabel: 'Tes 2 jeans',
    label: '2 jeans',
    reward: '10% sur toute la boutique',
  },
  {
    establishment: 'azul',
    article: model.BULK,
    successLabel: 'Ton tote-bag de textile',
    label: '1 tote-bag de textile en vrac',
    reward: '10% sur toute la boutique',
  },
  {
    establishment: 'azul',
    article: model.JEAN,
    successLabel: 'Tes 2 jeans',
    label: '2 jeans',
    reward: '10% sur toute la boutique',
  },
  {
    establishment: 'aussih',
    article: model.BULK,
    successLabel: 'Ton tote-bag de textile',
    label: '1 tote-bag de textile en vrac',
    reward: '10% sur toute la boutique',
  },
  {
    establishment: 'aussih',
    article: model.JEAN,
    successLabel: 'Tes 2 jeans',
    label: '2 jeans',
    reward: '10% sur toute la boutique',
  },
  {
    establishment: 'happesmoke_istres',
    article: model.BATTERY,
    successLabel: 'Tes 4 batteries de cigarette électronique',
    label: '4 batteries de cigarette électronique',
    reward: '10% sur la boutique',
  },
  {
    establishment: 'happesmoke_istres',
    article: model.MOD,
    successLabel: 'Ta cigarette électronique',
    label: '1 cigarette électronique',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide",
  },
  {
    establishment: 'happesmoke_istres',
    article: model.SMARTPHONE,
    successLabel: 'Ton smartphone',
    label: '1 smartphone',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide ",
  },
  {
    establishment: 'happesmoke_chateauneuf',
    article: model.BATTERY,
    successLabel: 'Tes 4 batteries de cigarette électronique',
    label: '4 batteries de cigarette électronique',
    reward: '10% sur la boutique',
  },
  {
    establishment: 'happesmoke_chateauneuf',
    article: model.MOD,
    successLabel: 'Ta cigarette électronique',
    label: '1 cigarette électronique',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide",
  },
  {
    establishment: 'happesmoke_chateauneuf',
    article: model.SMARTPHONE,
    successLabel: 'Ton smartphone',
    label: '1 smartphone',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide ",
  },
  {
    establishment: 'happesmoke_martigues',
    article: model.BATTERY,
    successLabel: 'Tes 4 batteries de cigarette électronique',
    label: '4 batteries de cigarette électronique',
    reward: '10% sur la boutique',
  },
  {
    establishment: 'happesmoke_martigues',
    article: model.MOD,
    successLabel: 'Ta cigarette électronique',
    label: '1 cigarette électronique',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide",
  },
  {
    establishment: 'happesmoke_martigues',
    article: model.SMARTPHONE,
    successLabel: 'Ton smartphone',
    label: '1 smartphone',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide ",
  },
  {
    establishment: 'happesmoke_uzes',
    article: model.BATTERY,
    successLabel: 'Tes 4 batteries de cigarette électronique',
    label: '4 batteries de cigarette électronique',
    reward: '10% sur la boutique',
  },
  {
    establishment: 'happesmoke_uzes',
    article: model.MOD,
    successLabel: 'Ta cigarette électronique',
    label: '1 cigarette électronique',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide",
  },
  {
    establishment: 'happesmoke_uzes',
    article: model.SMARTPHONE,
    successLabel: 'Ton smartphone',
    label: '1 smartphone',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide ",
  },
  {
    establishment: 'happesmoke_beaucaire',
    article: model.BATTERY,
    successLabel: 'Tes 4 batteries de cigarette électronique',
    label: '4 batteries de cigarette électronique',
    reward: '10% sur la boutique',
  },
  {
    establishment: 'happesmoke_beaucaire',
    article: model.MOD,
    successLabel: 'Ta cigarette électronique',
    label: '1 cigarette électronique',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide",
  },
  {
    establishment: 'happesmoke_beaucaire',
    article: model.SMARTPHONE,
    successLabel: 'Ton smartphone',
    label: '1 smartphone',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide ",
  },
  {
    establishment: 'happesmoke_marseille_bonneveine',
    article: model.BATTERY,
    successLabel: 'Tes 4 batteries de cigarette électronique',
    label: '4 batteries de cigarette électronique',
    reward: '10% sur la boutique',
  },
  {
    establishment: 'happesmoke_marseille_bonneveine',
    article: model.MOD,
    successLabel: 'Ta cigarette électronique',
    label: '1 cigarette électronique',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide",
  },
  {
    establishment: 'happesmoke_marseille_bonneveine',
    article: model.SMARTPHONE,
    successLabel: 'Ton smartphone',
    label: '1 smartphone',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide ",
  },
  {
    establishment: 'happesmoke_marseille_bourse',
    article: model.BATTERY,
    successLabel: 'Tes 4 batteries de cigarette électronique',
    label: '4 batteries de cigarette électronique',
    reward: '10% sur la boutique',
  },
  {
    establishment: 'happesmoke_marseille_bourse',
    article: model.MOD,
    successLabel: 'Ta cigarette électronique',
    label: '1 cigarette électronique',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide",
  },
  {
    establishment: 'happesmoke_marseille_bourse',
    article: model.SMARTPHONE,
    successLabel: 'Ton smartphone',
    label: '1 smartphone',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide ",
  },
  {
    establishment: 'happesmoke_mirabeau',
    article: model.BATTERY,
    successLabel: 'Tes 4 batteries de cigarette électronique',
    label: '4 batteries de cigarette électronique',
    reward: '10% sur la boutique',
  },
  {
    establishment: 'happesmoke_mirabeau',
    article: model.MOD,
    successLabel: 'Ta cigarette électronique',
    label: '1 cigarette électronique',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide",
  },
  {
    establishment: 'happesmoke_mirabeau',
    article: model.SMARTPHONE,
    successLabel: 'Ton smartphone',
    label: '1 smartphone',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide ",
  },
  {
    establishment: 'happesmoke_venelles',
    article: model.BATTERY,
    successLabel: 'Tes 4 batteries de cigarette électronique',
    label: '4 batteries de cigarette électronique',
    reward: '10% sur la boutique',
  },
  {
    establishment: 'happesmoke_venelles',
    article: model.MOD,
    successLabel: 'Ta cigarette électronique',
    label: '1 cigarette électronique',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide",
  },
  {
    establishment: 'happesmoke_venelles',
    article: model.SMARTPHONE,
    successLabel: 'Ton smartphone',
    label: '1 smartphone',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide ",
  },
  {
    establishment: 'happesmoke_bouc',
    article: model.BATTERY,
    successLabel: 'Tes 4 batteries de cigarette électronique',
    label: '4 batteries de cigarette électronique',
    reward: '10% sur la boutique',
  },
  {
    establishment: 'happesmoke_bouc',
    article: model.MOD,
    successLabel: 'Ta cigarette électronique',
    label: '1 cigarette électronique',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide",
  },
  {
    establishment: 'happesmoke_bouc',
    article: model.SMARTPHONE,
    successLabel: 'Ton smartphone',
    label: '1 smartphone',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide ",
  },
  {
    establishment: 'happesmoke_aubagne',
    article: model.BATTERY,
    successLabel: 'Tes 4 batteries de cigarette électronique',
    label: '4 batteries de cigarette électronique',
    reward: '10% sur la boutique',
  },
  {
    establishment: 'happesmoke_aubagne',
    article: model.MOD,
    successLabel: 'Ta cigarette électronique',
    label: '1 cigarette électronique',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide",
  },
  {
    establishment: 'happesmoke_aubagne',
    article: model.SMARTPHONE,
    successLabel: 'Ton smartphone',
    label: '1 smartphone',
    reward: "20% sur l'achat d'un nouveau KIT ou liquide ",
  },
  {
    establishment: 'office_depot_montgrand',
    article: model.TONER,
    label: '5 cartouches ou 5 toners',
    reward: '2,5€ pour 5 cartouches ou 5€ pour 5 toners',
    successLabel: 'Tes 5 cartouches ou 5 toners',
  },
  {
    establishment: 'office_depot_cantini',
    article: model.TONER,
    label: '5 cartouches ou 5 toners',
    reward: '2,5€ pour 5 cartouches ou 5€ pour 5 toners',
    successLabel: 'Tes 5 cartouches ou 5 toners',
  },
  {
    establishment: 'office_depot_aubagne',
    article: model.TONER,
    label: '5 cartouches ou 5 toners',
    reward: '2,5€ pour 5 cartouches ou 5€ pour 5 toners',
    successLabel: 'Tes 5 cartouches ou 5 toners',
  },
  {
    establishment: 'office_depot_toulon',
    article: model.TONER,
    label: '5 cartouches ou 5 toners',
    reward: '2,5€ pour 5 cartouches ou 5€ pour 5 toners',
    successLabel: 'Tes 5 cartouches ou 5 toners',
  },
  {
    establishment: 'office_depot_avignon',
    article: model.TONER,
    label: '5 cartouches ou 5 toners',
    reward: '2,5€ pour 5 cartouches ou 5€ pour 5 toners',
    successLabel: 'Tes 5 cartouches ou 5 toners',
  },
  {
    establishment: 'pantagruel',
    article: model.BULK,
    label: '1 tote-bag de textile',
    reward: "5% pour l'achat de 2 livres",
    successLabel: 'Ton tote-bag de textile',
  },
	  {
    establishment: 'odeur_du_temps',
    article: model.JEAN,
    label: '2 jeans',
    reward: "5% pour l'achat de 2 livres",
    successLabel: 'Tes 2 jeans',
  },
  {
    establishment: 'so_smoke',
    article: model.BATTERY,
    label: '4 batteries de cigarette électronique',
    reward: '15% sur la boutique',
    successLabel: 'Tes 4 batteries de cigarette électronique',
  },
  {
    establishment: 'so_smoke',
    article: model.MOD,
    successLabel: 'Ta cigarette électronique',
    label: '1 cigarette électronique',
    reward: '15% sur la boutique',
  },
  {
    establishment: 'prink',
    article: model.TONER,
    label: '4 cartouches ou 4 toners',
    reward: '5% sur la marque PRINK',
    successLabel: 'Tes 4 cartouches ou 4 toners',
  },
];

module.exports = collectingPoints;
